BZ #1712914 - command "hammer full-help" gives error "Error: undefined method `action' for false:FalseClass"
Fixes #26865 - action for false:FalseClass

(cherry picked from commit 943ea36b09cbc9516bb4201e155e79e1d7a7e410)